@startuml
participant Заказ_и_распределение_товара as Foo
actor       Оператор    as Foo1
actor       Менеджер    as Foo6
actor       Кладовщик   as Foo7
participant    Заказ    as Foo2
participant    Поступление     as Foo3
participant    Инвентаризация  as Foo4
participant    Место_хранения  as Foo5
Foo1 -> Foo6 : Формулировка задания
Foo1 -> Foo2 : Оформление заявки
Foo2 -> Foo3 : Перемещение товара
Foo6 -> Foo4 : Распределение
Foo4 -> Foo7 : Формулировка задания
Foo7 -> Foo5 : Распредение на конечную точку
@enduml

@startuml
actor Оператор
actor Менеджер
actor Кладовщик
node ПК_оператора
node ПК_менеджера
node ПК_кладовщика

database ИС_склада
Оператор -- ПК_оператора: Вход на платформу
Менеджер -- ПК_менеджера: Вход на платформу
Кладовщик -- ПК_кладовщика: Вход на платформу
ПК_оператора -- ИС_склада: Оформление заявки
ПК_менеджера -- ИС_склада: Формулировка задания
ПК_оператора -- ПК_менеджера: Детали заявки
ПК_кладовщика -- ИС_склада: Детали заказа
@enduml