@startuml
left to right direction
skinparam packageStyle rect
actor Менеджер
actor Кладовщик
actor Оператор
rectangle ИС {
Оператор --> (Поступление)
Оператор --> (Уход со склада)
Оператор --> (Списание)
Оператор --> (Инвентаризация)
Менеджер --> (Поступление)
Менеджер --> (Уход со склада)
Кладовщик --> (Инвентаризация)
Кладовщик --> (Списание)
Кладовщик --> (Место хранения)
(Списание товара) .> (Уход со склада)
(Инвентаризация) .> (Место хранения)
}
@enduml

@startuml
skinparam packageStyle rect
class Место_хранения {
Код товара
Стеллаж
Ячейка
}
class Инвентаризация {
Код товара
Код оператора
Код кладовщика
Дата, время
}
class Уход_со_склада {
Код списания
Количество
Дата/время
}
class Поступление {
Код поставки
Код поставщика
Код менеджера
Дата поставки
Наименование товара
}
class Работники{
Код пользователя
ФИО
Логин
Пароль
Роль
}
Поступление <.. Работники
Инвентаризация <.. Работники
Уход_со_склада <.. Работники
Место_хранения <.. Инвентаризация
Уход_со_склада <.. Поступление
Инвентаризация <.. Уход_со_склада
Уход_со_склада <.. Инвентаризация
Уход_со_склада <.. Место_хранения
@enduml

@startuml
participant Заказ_и_распределение_товара as Foo
actor       Оператор    as Foo1
actor       Менеджер    as Foo6
actor       Кладовщик   as Foo7
participant    Заказ    as Foo2
participant    Поступление     as Foo3
participant    Инвентаризация  as Foo4
participant    Место_хранения  as Foo5
Foo1 -> Foo6 : Формулировка задания
Foo1 -> Foo2 : Оформление заявки
Foo2 -> Foo3 : Перемещение товара
Foo6 -> Foo4 : Распределение
Foo4 -> Foo7 : Формулировка задания
Foo7 -> Foo5 : Распредение на конечную точку
@enduml